CREATE DATABASE IF NOT EXISTS hms;

USE HMS;

CREATE TABLE ROLES(
  ROLE_ID INT PRIMARY KEY AUTO_INCREMENT,
  ROLE_NAME VARCHAR(30) UNIQUE
);

CREATE TABLE USERS(
USER_ID INT PRIMARY KEY AUTO_INCREMENT,
USER_NAME VARCHAR(20) UNIQUE,
USER_PASSWORD VARCHAR(255) NOT NULL,

ROLE_ID INT,

FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID),

CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DOCTORS(
DOCTOR_ID INT PRIMARY KEY AUTO_INCREMENT,
DOCTOR_NAME VARCHAR(50) NOT NULL,
SPECIALIZATION VARCHAR(50) NOT NULL,

USER_ID INT UNIQUE,

FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) 
ON DELETE CASCADE 
ON UPDATE CASCADE
);


CREATE TABLE PATIENTS(
PATIENT_ID INT PRIMARY KEY AUTO_INCREMENT,
PATIENT_NAME VARCHAR(50) NOT NULL,

PATIENT_AGE INT NOT NULL
CHECK(PATIENT_AGE BETWEEN 0 AND 100),

PATIENT_GENDER ENUM('MALE','FEMALE','OTHER'),
PATIENT_BLOOD_GROUP ENUM('A+','B+','AB+','O+','O-','AB-','A-','B-'),

CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE APPOINTMENT(
APPOINTMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
APPOINTMENT_DATE DATETIME NOT NULL,
CONSULTATION_FEE DECIMAL(10,2) NOT NULL,

APPOINTMENT_STATUS ENUM('SCHEDULED','CONFIRMED','PENDING','COMPLETED','CANCELLED','NO SHOW','RESCHEDULED'), 

PATIENT_ID INT,
DOCTOR_ID INT,

FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
ON DELETE CASCADE 
ON UPDATE CASCADE,

FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID)
ON DELETE CASCADE 
ON UPDATE CASCADE,

CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LABORATORY(
LAB_ID INT PRIMARY KEY AUTO_INCREMENT,
LAB_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE TESTS(
TEST_ID INT PRIMARY KEY AUTO_INCREMENT,
TEST_NAME VARCHAR(70) NOT NULL,
TEST_FEE DECIMAL(10,2) NOT NULL,

LAB_ID INT,

FOREIGN KEY (LAB_ID) REFERENCES LABORATORY (LAB_ID)
ON DELETE CASCADE 
ON UPDATE CASCADE

);
 
CREATE TABLE TEST_RECORDS(
RECORD_ID INT PRIMARY KEY AUTO_INCREMENT,
TEST_DATE DATETIME,
TEST_STATUS ENUM('PENDING','IN PROCESS','COMPLETED'),
TEST_RESULT ENUM('POSITIVE','NEGATIVE','INCONCLUSIVE','NOT DONE'),
PATIENT_ID INT,
DOCTOR_ID INT,
TEST_ID INT,

FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
ON DELETE CASCADE 
ON UPDATE CASCADE,

FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID)
ON DELETE CASCADE 
ON UPDATE CASCADE,

FOREIGN KEY (TEST_ID) REFERENCES TESTS(TEST_ID)
ON DELETE CASCADE 
ON UPDATE CASCADE,

CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BILLS (
BILL_ID INT NOT NULL AUTO_INCREMENT,
PATIENT_ID INT NOT NULL,
CONSULTATION_FEE DECIMAL(10,2) DEFAULT 0.00,
TEST_FEE DECIMAL(10,2) DEFAULT 0.00,
TOTAL_AMOUNT DECIMAL(10,2) NOT NULL DEFAULT 0.00,
PAYMENT_STATUS ENUM('Pending','Paid','Partial') DEFAULT 'Pending',
BILL_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY (BILL_ID),
INDEX idx_patient (PATIENT_ID),
CONSTRAINT bills_fk_patient

FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);